export const seedData = {
  users: [
    {
      id: crypto.randomUUID(),
      name: "Legal Admin",
      email: "admin@company.com",
      role: "Admin",
      department: "Legal",
      status: "Active",
      password: "admin123",
      createdAt: new Date().toISOString(),
    },
    {
      id: crypto.randomUUID(),
      name: "Contract Reviewer",
      email: "reviewer@company.com",
      role: "Reviewer",
      department: "Legal",
      status: "Active",
      password: "review123",
      createdAt: new Date().toISOString(),
    },
  ],
  matters: [
    {
      id: crypto.randomUUID(),
      matterNo: "MAT-2026-0001",
      title: "Supplier dispute - ABC Co",
      type: "Dispute",
      owner: "Legal Team",
      department: "Procurement",
      status: "Open",
      openedDate: "2026-03-10",
      priority: "High",
      description: "Reviewing commercial obligations and dispute response.",
      createdAt: new Date().toISOString(),
    },
  ],
  documents: [
    {
      id: crypto.randomUUID(),
      documentNo: "DOC-2026-0001",
      title: "Master Service Agreement",
      category: "Contract",
      matterNo: "MAT-2026-0001",
      version: "1.0",
      status: "Pending Review",
      confidentiality: "Confidential",
      fileName: "msa.pdf",
      fileSize: 240000,
      uploadedBy: "Legal Admin",
      uploadedAt: new Date().toISOString(),
      notes: "Initial draft uploaded for review.",
    },
  ],
  contracts: [
    {
      id: crypto.randomUUID(),
      contractNo: "CON-2026-0001",
      title: "Annual Maintenance Agreement",
      counterparty: "ABC Company",
      matterNo: "MAT-2026-0001",
      effectiveDate: "2026-01-01",
      expiryDate: "2026-12-31",
      value: "15000",
      currency: "KWD",
      status: "Active",
      renewalNoticeDays: "60",
      owner: "Legal Team",
      createdAt: new Date().toISOString(),
    },
  ],
  auditLogs: [
    {
      id: crypto.randomUUID(),
      timestamp: new Date().toISOString(),
      module: "System",
      action: "Initialize",
      entityCode: "SEED",
      performedBy: "System",
      details: "Seed data created",
    },
  ],
};